# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: /images/posters
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

